import './globals.css'
import '@radix-ui/themes/styles.css'
import '@radix-ui/colors/gray.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { Theme } from '@radix-ui/themes'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Theme appearance="light" accentColor="orange" panelBackground="solid">
          {children}
        </Theme>
      </body>
    </html>
  )
}
